image: Visual Studio 2019
skip_commits:
  message: /docs|Merge pull request.*/
build_script:
- cmd: dotnet build src --configuration Release
test:
  categories:
    except:
    - Integration
artifacts:
- path: nugets\*.nupkg